### ISSUE TITLE
Mustn't go outside of visible viewport

### ISSUE THREAD

**Issue by adam-lynch** [HubSpot/tooltip#30]
i.e. if you want it positioned to the right of an element which is against the right-side of the page, then it should be moved to the top / bottom. 

I would've assumed since this relies on Tether that this would already be a given.

**Comment by zackbloom** [comment]
You can always pass Tether options as `tetherOptions: {}`.

**Comment by ashclarke** [comment]
![image](https://cloud.githubusercontent.com/assets/963023/5979430/7bb0933a-a89f-11e4-9cea-727255767bfa.png)

I have a similar problem with center-bottom attached tooltips going offscreen on the left (because the width of the target element (<a>) is smaller than the tooltip width.

Is it possible to prevent this? I've tried the tether options but I can't work out which constraints to use.

I don't really want to set the width of the <a> tag because I don't want the clickable area to extend past the end of the text.

**Comment by mrdoinel** [comment]
I have the same issue.

I tried to set the tetherOptions but it is not working :
```
tetherOptions: {
    constraints: [
        {
            to: 'window'
        }
     ]
}
```

The tooltip keep displaying at the same place.

**Comment by mrdoinel** [comment]
Also I checked and the tooltip has the option `constrainToWindow: true` (but still goes outside)

**Comment by geekjuice** [comment]
Related https://github.com/HubSpot/drop/issues/16. Since `tooltip` uses `drop`, fixing the issue in `drop` should fix the issues in `tooltip` as well.
