### ISSUE TITLE
Tooltip vs. Drop

### ISSUE THREAD

**Issue by dandv** [HubSpot/tooltip#41]
http://github.hubspot.com/drop/overview/drop_vs_tether/ is great.

A similar page detailing how Tooltip builds upon Drop would be great too.

**Comment by geekjuice** [comment]
To be really honest, `tooltip` is _barely_ a wrapper around `drop`. In fact, one of the main difference between the two (IMHO) is the addition of `pointer-event: none` in the `tooltip` styles making them feel more like transitional popovers. If you think the difference still merits a `drop vs tooltip`, I'll be more than happy to write a small gist in the docs.

Otherwise, feel free to take a look at the source code for `tooltip` to see how it's basically just a proxy for `drop`.
